_XimEncodingNegotiation: swap order of arguments to calloc
Avoids build failures with gcc 14.2 when MALLOC_0_RETURNS_NULL is defined:

imDefIm.c: In function ‘_XimEncodingNegotiation’:
imDefIm.c:1739:15: error: ‘memcpy’ offset 8 is out of the bounds [0, 1]
 [-Werror=array-bounds=]
 1739 |         (void)memcpy((char *)&buf_s[2], name_ptr, name_len);
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>
Part-of: <https://gitlab.freedesktop.org/xorg/lib/libx11/-/merge_requests/267>