_XimStrConversionCallback: use size_t to calculate size to malloc
Avoids build failures with gcc 14.2 when MALLOC_0_RETURNS_NULL is defined:

imCallbk.c:346:9: error: ‘memcpy’ offset 10 is out of the bounds [0, 1]
 [-Werror=array-bounds=]
  346 |         memcpy(&buf[p],&cbrec.text->string.mbs,length_in_bytes);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>
Part-of: <https://gitlab.freedesktop.org/xorg/lib/libx11/-/merge_requests/267>