_XlcDefaultMapModifiers: remove conversions between size_t & int
Avoids build failures with gcc 14.2 when MALLOC_0_RETURNS_NULL is defined:

lcWrap.c: In function ‘_XlcDefaultMapModifiers’:
lcWrap.c:149:9: warning: ‘strcpy’ writing between 4294967296 and
 9223372036854775806 bytes into a region of size 1 [-Wstringop-overflow=]
  149 |         strcpy(mods, prog_mods);
      |         ^~~~~~~~~~~~~~~~~~~~~~~
../../include/X11/Xlibint.h:457:24: note: destination object of size 1
 allocated by ‘malloc’
  457 | # define Xmalloc(size) malloc((size_t)((size) == 0 ? 1 : (size)))
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lcWrap.c:147:12: note: in expansion of macro ‘Xmalloc’
  147 |     mods = Xmalloc(i);
      |            ^~~~~~~
lcWrap.c:149:9: error: ‘__builtin_memcpy’ forming offset [1, 4294967295]
 is out of the bounds [0, 1] [-Werror=array-bounds=]
  149 |         strcpy(mods, prog_mods);
      |         ^~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>
Part-of: <https://gitlab.freedesktop.org/xorg/lib/libx11/-/merge_requests/267>